const photoFiles=[];
const P=''; let pin='',flowers=[];
const keys=document.querySelector('.keys');[1,2,3,4,5,6,7,8,9,'⌫',0,'♥'].forEach(k=>{let b=document.createElement('button');b.textContent=k;b.onclick=()=>{if(k==='⌫')pin=pin.slice(0,-1);else if(k!=='♥'&&pin.length<4)pin+=k;renderDots()};keys.appendChild(b)});
function renderDots(){document.querySelector('#dots').textContent=[0,1,2,3].map(i=>i<pin.length?'●':'○').join(' ')}
const bgMusic=document.querySelector('#bgMusic'), musicToggle=document.querySelector('#musicToggle');
function startMusic(){bgMusic.volume=.65;bgMusic.muted=false;const p=bgMusic.play();musicToggle.style.display='block';if(p!==undefined)p.then(()=>{musicToggle.textContent='♫'}).catch(()=>{musicToggle.textContent='▶';musicToggle.title='Tap to play music'})}
musicToggle.onclick=()=>{bgMusic.muted=false;if(bgMusic.paused){bgMusic.play().then(()=>musicToggle.textContent='♫').catch(()=>musicToggle.textContent='▶')}else{bgMusic.pause();musicToggle.textContent='▶'}};
document.querySelector('#unlock').onclick=()=>{if(pin==='0110'){bgMusic.load();bgMusic.volume=.65;bgMusic.muted=false;const playPromise=bgMusic.play();musicToggle.style.display='block';if(playPromise!==undefined){playPromise.then(()=>musicToggle.textContent='♫').catch(()=>musicToggle.textContent='▶')}go('letter')}else{document.querySelector('#err').textContent='Not quite… think of our special date ♥';pin='';renderDots()}};
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.querySelector('#'+id).classList.add('active');scrollTo(0,0);if(id==='memories')setTimeout(initScratch,80)}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
const mg=document.querySelector('#memorygrid');photoFiles.slice(0,6).forEach((f,i)=>{let d=document.createElement('div');d.className='scratch';d.style.setProperty('--r',`${[-3,2,-1,3,-2,1][i]}deg`);d.innerHTML=`<img src="${P+f}"><canvas></canvas><span>${['Our beginning','Your smile','Us being us','A favorite day','Tiny moments','Always us'][i]} ♡</span><em class="scratch-progress">scratch me ♡</em>`;mg.appendChild(d)});
function initScratch(){document.querySelectorAll('.scratch').forEach((d,i)=>{if(d.dataset.ready)return;d.dataset.ready='1';const c=d.querySelector('canvas'),ctx=c.getContext('2d');function paint(){const r=d.querySelector('img').getBoundingClientRect();const scale=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,Math.round(r.width*scale));c.height=Math.max(1,Math.round(r.height*scale));ctx.setTransform(scale,0,0,scale,0,0);ctx.globalCompositeOperation='source-over';let g=ctx.createLinearGradient(0,0,r.width,r.height);g.addColorStop(0,['#ef91b0','#e8a8bf','#f0b8cb'][i%3]);g.addColorStop(1,'#d86e94');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);ctx.fillStyle='#fff';ctx.font='700 17px Georgia';ctx.textAlign='center';ctx.fillText('scratch me ♡',r.width/2,r.height/2);ctx.font='12px Arial';ctx.fillText('swipe your finger',r.width/2,r.height/2+24)}paint();let down=false,moves=0;const scratch=e=>{if(!down)return;e.preventDefault();const r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.arc((p.clientX-r.left)*(c.width/r.width)/(devicePixelRatio||1),(p.clientY-r.top)*(c.height/r.height)/(devicePixelRatio||1),30,0,Math.PI*2);ctx.fill();moves++;if(moves>28){d.classList.add('revealed');d.querySelector('.scratch-progress').textContent='revealed ♥'}};c.addEventListener('pointerdown',e=>{down=true;c.setPointerCapture?.(e.pointerId);scratch(e)});c.addEventListener('pointermove',scratch);c.addEventListener('pointerup',()=>down=false);c.addEventListener('pointercancel',()=>down=false);window.addEventListener('resize',paint,{passive:true})})}
const loveNote=document.querySelector('#loveNote');function openLoveNote(){loveNote.classList.add('open');loveNote.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeLoveNote(){loveNote.classList.remove('open');loveNote.setAttribute('aria-hidden','true');document.body.style.overflow=''}document.querySelector('#loveClose').onclick=closeLoveNote;loveNote.addEventListener('click',e=>{if(e.target===loveNote)closeLoveNote()});
const flowerGift=document.querySelector('#flowerGift');function openFlowerGift(){flowerGift.classList.add('open');flowerGift.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeFlowerGift(){flowerGift.classList.remove('open');flowerGift.setAttribute('aria-hidden','true');document.body.style.overflow=''}document.querySelector('#flowerGiftClose').onclick=closeFlowerGift;flowerGift.addEventListener('click',e=>{if(e.target===flowerGift)closeFlowerGift()});
document.querySelectorAll('.gift').forEach(b=>b.onclick=()=>{if(b.dataset.g==='camera'){openReel();return}if(b.dataset.g==='letter'){openLoveNote();return}if(b.dataset.g==='flower'){openFlowerGift();return}});
const reel=document.querySelector('#reel'),reelImg=document.querySelector('#reelImg'),reelText=document.querySelector('#reelText'),reelCount=document.querySelector('#reelCount'),reelProgress=document.querySelector('#reelProgress');let reelIndex=0,reelTimer=null;const reelLines=['Where our story lives ❤️','That smile I could never forget','Just us, being us','A day worth keeping forever','The little moments matter most','My favorite kind of happiness','Every picture has a heartbeat','You make ordinary days special','A thousand smiles, one us','Still choosing you ❤️','Memories I would replay forever','My favorite person','Us, in our own little world','And the story keeps going…','Sanjir ♥ Simran — 01.10'];
function buildReelProgress(){reelProgress.innerHTML=photoFiles.map(()=>'<i></i>').join('')}
function showReel(i){reelIndex=(i+photoFiles.length)%photoFiles.length;reelImg.classList.remove('reel-pop');void reelImg.offsetWidth;reelImg.src=P+photoFiles[reelIndex];reelImg.classList.add('reel-pop');reelText.textContent=reelLines[reelIndex]||'Our memory ❤️';reelCount.textContent=`${reelIndex+1} / ${photoFiles.length}`;reelProgress.querySelectorAll('i').forEach((x,n)=>x.className=n<reelIndex?'done':n===reelIndex?'now':'');clearTimeout(reelTimer);reelTimer=setTimeout(()=>{if(reelIndex===photoFiles.length-1)closeReel();else showReel(reelIndex+1)},3200)}
function openReel(){buildReelProgress();reel.classList.add('open');reel.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';showReel(0)}function closeReel(){clearTimeout(reelTimer);reel.classList.remove('open');reel.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelector('#reelClose').onclick=closeReel;document.querySelector('#reelNext').onclick=()=>showReel(reelIndex+1);document.querySelector('#reelPrev').onclick=()=>showReel(reelIndex-1);
let touchX=0;reel.addEventListener('touchstart',e=>touchX=e.touches[0].clientX,{passive:true});reel.addEventListener('touchend',e=>{let d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>45)showReel(reelIndex+(d<0?1:-1))},{passive:true});
const flowerColors={'🌹':'#d83b57','🌷':'#f0719a','🌸':'#f6a8c6','🌺':'#e84f7b','🌻':'#f3b52f','🌼':'#fff1a8','💐':'#bd73cf'};
function renderBouquet(target,large=false){target.innerHTML='<div class="bouquet-paper"></div><div class="bouquet-ribbon">🎀</div>';let arr=flowers;arr.forEach((x,i)=>{let angle=(-34+(i%7)*11)+(Math.floor(i/7)*4), left=100+(i%3-1)*12, bottom=128+(i%4)*13;let stem=document.createElement('span');stem.className='stem';stem.style.transform=`rotate(${angle}deg)`;target.appendChild(stem);let f=document.createElement('span');f.className='petal-flower';f.style.setProperty('--petal',flowerColors[x]||'#ed8fb3');f.style.left=left+'px';f.style.bottom=bottom+'px';f.style.transform=`translate(${(i%5-2)*12}px,${-Math.floor(i/5)*18}px) scale(${.82+(i%3)*.08})`;f.innerHTML='<i></i><i></i><i></i><i></i><i></i><b></b>';target.appendChild(f)})}
document.querySelectorAll('.palette button').forEach(b=>b.onclick=()=>{if(flowers.length<14){flowers.push(b.textContent);renderBouquet(document.querySelector('#picked'))}});renderBouquet(document.querySelector('#picked'));
document.querySelector('#finish').onclick=()=>{const big=document.querySelector('#bigbouquet');big.textContent='';big.className='bigbouquet premium';let stage=document.createElement('div');stage.className='bouquet-stage';big.appendChild(stage);renderBouquet(stage,true);go('final')};
const gal=document.querySelector('#gallery');photoFiles.forEach(f=>gal.innerHTML+=`<img src="${P+f}">`);document.querySelector('#restart').onclick=()=>{pin='';flowers=[];renderDots();renderBouquet(document.querySelector('#picked'));go('lock')};
setInterval(()=>{let h=document.createElement('span');h.className='heart';h.textContent=Math.random()>.5?'♡':'♥';h.style.left=Math.random()*100+'vw';h.style.fontSize=(12+Math.random()*20)+'px';h.style.animationDuration=(5+Math.random()*5)+'s';document.body.appendChild(h);setTimeout(()=>h.remove(),10000)},650);
